### ISSUE TITLE
一直卡住

### ISSUE THREAD

**Issue by 99yhf** [sliva0/pixelart2tgs#2]
^CTraceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.10/site-packages/pixelart2tgs/__main__.py", line 194, in <module>
    main()
  File "/opt/homebrew/lib/python3.10/site-packages/pixelart2tgs/__main__.py", line 185, in main
    lottie = generate_lottie(source, args.label)  # type: ignore
  File "/opt/homebrew/lib/python3.10/site-packages/pixelart2tgs/lottie_generator.py", line 32, in generate_lottie
    durations, shape_dict = generate_shapes(source)
  File "/opt/homebrew/lib/python3.10/site-packages/pixelart2tgs/shape_generator.py", line 95, in generate_shapes
    frames_shapes = list(map(extract_frame_shapes, frames))
  File "/opt/homebrew/lib/python3.10/site-packages/pixelart2tgs/shape_generator.py", line 77, in extract_frame_shapes
    shape, shape_shift = normalize_shape(labels == label_number)
  File "/opt/homebrew/lib/python3.10/site-packages/pixelart2tgs/shape_generator.py", line 54, in normalize_shape
    coords = shape.nonzero()  # get transposed coords of ones in shape
KeyboardInterrupt

**Comment by sliva0** [comment]
This is Python's standard response to pressing Ctrl+C. I see no reason to do anything about it.
